### ISSUE TITLE
NameError: name 'unibigram' is not defined in Paper Version

### ISSUE THREAD

**Issue by duanyanan** [diningphil/CGMM#2]
I download Paper Version code, and I run as `python Main.py`, then it raise error as
```Training Layer 1
Likelihood at epoch 1 : -428872.712890625
Likelihood at epoch 2 : -253869.62939453125
Likelihood at epoch 3 : -253866.67578125
Likelihood at epoch 4 : -253874.48291015625
Training Layer 2
Likelihood at epoch 1 : -579436.9619140625
Likelihood at epoch 2 : -327025.16259765625
Likelihood at epoch 3 : -313134.9091796875
Likelihood at epoch 4 : -299116.97216796875
Likelihood at epoch 5 : -285301.2666015625
Likelihood at epoch 6 : -272734.00341796875
Likelihood at epoch 7 : -262256.85986328125
Likelihood at epoch 8 : -254079.62109375
Likelihood at epoch 9 : -247836.68603515625
Likelihood at epoch 10 : -242978.4423828125
Training Layer 3
Likelihood at epoch 1 : -598459.7802734375
Likelihood at epoch 2 : -310831.02587890625
Likelihood at epoch 3 : -286313.6552734375
Likelihood at epoch 4 : -262403.83984375
Likelihood at epoch 5 : -242790.5224609375
Likelihood at epoch 6 : -228331.54248046875
Likelihood at epoch 7 : -217802.17724609375
Likelihood at epoch 8 : -210491.32421875
Likelihood at epoch 9 : -205836.2421875
Likelihood at epoch 10 : -203036.69873046875
Training Layer 4
Likelihood at epoch 1 : -753160.71484375
Likelihood at epoch 2 : -315933.31640625
Likelihood at epoch 3 : -282933.55517578125
Likelihood at epoch 4 : -255435.091796875
Likelihood at epoch 5 : -229706.66943359375
Likelihood at epoch 6 : -206927.2900390625
Likelihood at epoch 7 : -189161.599609375
Likelihood at epoch 8 : -177048.791015625
Likelihood at epoch 9 : -169296.32763671875
Likelihood at epoch 10 : -164141.34130859375
Inference: layer 1
Traceback (most recent call last):
  File "Main.py", line 95, in <module>
    exp_name, tr_val_test='train', architecture=None, save_name=save_name)
  File "/home/anyua/dyn/CGMM-0.9/utils/CGMMUtilities.py", line 292, in incremental_inference
    aggregate_posteriors=infer_with_posterior, bigram=bigram),
  File "/home/anyua/dyn/CGMM-0.9/utils/CGMMUtilities.py", line 30, in _aggregate_states
    if unibigram:
NameError: name 'unibigram' is not defined
```
I wonder that maybe some files are absent?

**Comment by diningphil** [comment]
There has been an error when refactoring the code. You should sholve this by changing the default argument of _aggregate_states to "unibigram" instead of "bigram". Let me know if that works

**Comment by duanyanan** [comment]
Thanks a lot! It works. For details, I change ```def _aggregate_states(C, adj_lists, sizes, states, statistics=None, aggregate_posteriors=False, bigram=False)``` to 
```def _aggregate_states(C, adj_lists, sizes, states, statistics=None, aggregate_posteriors=False, unibigram=False)``` at the defination of _aggregate_states. And in the caller `incremental_inference` I change the line about `_aggregate_states` to 
`save_tensor(_aggregate_states(cgmm_layer.C, adjacency_lists, sizes,
                                      posteriors if infer_with_posterior else inferred_states,
                                      statistics=statistics if bigram else None,
                                      aggregate_posteriors=infer_with_posterior, unibigram=bigram),
                    exp_name, unigram_folder, unigram_filename, layer)`
It can behave normally. thx~ :)
